### PR TITLE
folder restructure

### PR DESCRIPTION
**Pull request by dinesh-07**

### CODE REVIEW

**Comment by dinesh-07** [comment]
Change in folder structure

**Comment by AadishJain249** [comment]
@dinesh-07 U have changed the readme file copy readme from my repo and then merge the pr

**Comment by dinesh-07** [comment]
Oh my bad, I mistakenly kept the inner one. I will fix it now.

**Comment by dinesh-07** [comment]
I just updated, please check and approve PR.

**Comment by AadishJain249** [comment]
@dinesh-07 Thanx for contributing

**Pull request merged**
