### PR TITLE
Replace react-currency-format to fix #2

### LINKED ISSUE #2: Handle React Currency Format Error

### PR DESCRIPTION
**Pull request by IanFindlay**
Fixes #2 - replaced react-currency-format with a utility method and some inline logic.

## Home Page:
amazon-home  
  
## Basket:
amazon-basket

### CODE REVIEW

**Comment by AadishJain249** [comment]
@IanFindlay Please address merge conflict issue
image

**Comment by AadishJain249** [comment]
image

@IanFindlay  in subtotal.js file don't remove color theme of the component revert it and the rest of the things are fine 
Happy Coding!

**Comment by IanFindlay** [comment]
Sorry about that, somehow failed to see the theme stuff when I was dealing with the conflicts. I believe everything should be good now but let me know if it isn't.

**Comment by AadishJain249** [comment]
@IanFindlay thanx for contributing to project Happy Coding!

**Pull request merged**
